# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos9810-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter starlte star2lte,$(TARGET_DEVICE)),)

endif
